// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDZqpMEtfWihqo4Zwf_5kr4ThdjT4SAHio',
    appId: '1:357670403502:web:6b23ab2c043426e3f95c3f',
    messagingSenderId: '357670403502',
    projectId: 'myada-88789',
    authDomain: 'myada-88789.firebaseapp.com',
    storageBucket: 'myada-88789.firebasestorage.app',
    measurementId: 'G-1FKGZZ0GFV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBdPbyUZdKrQBCecCbzYRMhd9BeQ3BBO34',
    appId: '1:357670403502:android:201d84e556506cb3f95c3f',
    messagingSenderId: '357670403502',
    projectId: 'myada-88789',
    storageBucket: 'myada-88789.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBpJeGB8YH1OGO8Md1AG6yLKpr1EHQB5Rg',
    appId: '1:357670403502:ios:fb9580764609d8c0f95c3f',
    messagingSenderId: '357670403502',
    projectId: 'myada-88789',
    storageBucket: 'myada-88789.firebasestorage.app',
    iosBundleId: 'com.example.myAda',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBpJeGB8YH1OGO8Md1AG6yLKpr1EHQB5Rg',
    appId: '1:357670403502:ios:fb9580764609d8c0f95c3f',
    messagingSenderId: '357670403502',
    projectId: 'myada-88789',
    storageBucket: 'myada-88789.firebasestorage.app',
    iosBundleId: 'com.example.myAda',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDZqpMEtfWihqo4Zwf_5kr4ThdjT4SAHio',
    appId: '1:357670403502:web:1e989368d193a364f95c3f',
    messagingSenderId: '357670403502',
    projectId: 'myada-88789',
    authDomain: 'myada-88789.firebaseapp.com',
    storageBucket: 'myada-88789.firebasestorage.app',
    measurementId: 'G-19TDY3MY7T',
  );

}